# This file was generated by GoReleaser. DO NOT EDIT.
cask "launchd-gen" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/VandyTheCoder/launchd-gen/releases/download/v#{version}/launchd-gen_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/VandyTheCoder/launchd-gen"
      sha256 "b5b335e4bef1014b05b5c0baaa1a7c491b0221d756538256c15c5c24e3f86fe3"
    end
    on_arm do
      url "https://github.com/VandyTheCoder/launchd-gen/releases/download/v#{version}/launchd-gen_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/VandyTheCoder/launchd-gen"
      sha256 "646a8b03c46007947879c8737fe5aa0fc9f7277bae34607bd7e5652924b1929e"
    end
  end

  name "launchd-gen"
  desc "Convert cron expressions into macOS launchd plists"
  homepage "https://github.com/VandyTheCoder/launchd-gen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "launchd-gen"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/launchd-gen"]
    end
  end

  # No zap stanza required

end
